steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/etl-hacker-quest-ipnet:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/etl-hacker-quest-ipnet:latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'etl-hacker-quest-service',
        '--image', 'gcr.io/$PROJECT_ID/etl-hacker-quest-ipnet:latest',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--service-account', 'guilhermecarvalho-admin@etl-hacker-quest-ipnet.iam.gserviceaccount.com'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
logsBucket: gs://logs-challenge-bucket