default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: etl-hacker-quest-ipnet
      dataset: etl_hackerquest
      threads: 4
      keyfile: /home/guilherme/challenge-hacker-quest-ipnet/credentials/key.json
      location: US
