data_raw_directory: 'raw'
data_validation_directory: 'raw_validation'

project_id: 'etl-hacker-quest-ipnet'
dataset_id: 'etl_hackerquest'
bucket_name: 'bucket_data_challenge'

file_delimiter_mapping:
  hackers.csv: '|'
