data_raw_directory: 'data/raw'
data_validation_directory: 'data/raw_validation'

project_id: 'etl-hacker-quest-ipnet'
dataset_id: 'etl_hackerquest'

credentials_path: 'credentials/key.json'
bucket_name: 'etl-validated-data'
