project_id: 'etl-hacker-quest-ipnet'
dataset_id: 'etl_hackerquest'
bucket_name: 'datalake'

bronze_folder: 'bronze_layer/'
silver_folder: 'silver_layer/'
gold_folder: 'gold_layer/'

file_delimiter_mapping:
  hackers.csv: '|'